# Generated by Django 3.0.7 on 2020-06-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200625_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('T', 'Todo'), ('P', 'Progress'), ('D', 'Done')], max_length=1),
        ),
    ]
