# Generated by Django 3.0.7 on 2020-06-29 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20200629_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_modified_by',
        ),
    ]
